'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.CalculadoraServiceSoap")>  _
    Public Interface CalculadoraServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suma", ReplyAction:="*")>  _
        Function suma(ByVal n1 As Double, ByVal n2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suma", ReplyAction:="*")>  _
        Function sumaAsync(ByVal n1 As Double, ByVal n2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function Resta(ByVal n1 As Double, ByVal n2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal n1 As Double, ByVal n2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/fac", ReplyAction:="*")>  _
        Function fac(ByVal n As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/fac", ReplyAction:="*")>  _
        Function facAsync(ByVal n As Integer) As System.Threading.Tasks.Task(Of Double)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento divResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/div", ReplyAction:="*")>  _
        Function div(ByVal request As ServiceReference1.divRequest) As ServiceReference1.divResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/div", ReplyAction:="*")>  _
        Function divAsync(ByVal request As ServiceReference1.divRequest) As System.Threading.Tasks.Task(Of ServiceReference1.divResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function Multiplicacion(ByVal n1 As Double, ByVal n2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function MultiplicacionAsync(ByVal n1 As Double, ByVal n2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function Potencia(ByVal Base As Double, ByVal Exponente As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function PotenciaAsync(ByVal Base As Double, ByVal Exponente As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RaizCuadrada", ReplyAction:="*")>  _
        Function RaizCuadrada(ByVal Radicando As Double, ByVal indice As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RaizCuadrada", ReplyAction:="*")>  _
        Function RaizCuadradaAsync(ByVal Radicando As Double, ByVal indice As Double) As System.Threading.Tasks.Task(Of Double)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento InversoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Inverso", ReplyAction:="*")>  _
        Function Inverso(ByVal request As ServiceReference1.InversoRequest) As ServiceReference1.InversoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Inverso", ReplyAction:="*")>  _
        Function InversoAsync(ByVal request As ServiceReference1.InversoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.InversoResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function Seno(ByVal n1 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function SenoAsync(ByVal n1 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function Coseno(ByVal n1 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function CosenoAsync(ByVal n1 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function Tangente(ByVal n1 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function TangenteAsync(ByVal n1 As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class divRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="div", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.divRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.divRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class divRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public n1 As Double
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public n2 As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal n1 As Double, ByVal n2 As Double)
            MyBase.New
            Me.n1 = n1
            Me.n2 = n2
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class divResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="divResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.divResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.divResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class divResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public divResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal divResult As String)
            MyBase.New
            Me.divResult = divResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class InversoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Inverso", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.InversoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.InversoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InversoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public n1 As Double
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal n1 As Double)
            MyBase.New
            Me.n1 = n1
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class InversoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="InversoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.InversoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.InversoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InversoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public InversoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal InversoResult As String)
            MyBase.New
            Me.InversoResult = InversoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CalculadoraServiceSoapChannel
        Inherits ServiceReference1.CalculadoraServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalculadoraServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.CalculadoraServiceSoap)
        Implements ServiceReference1.CalculadoraServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function suma(ByVal n1 As Double, ByVal n2 As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.suma
            Return MyBase.Channel.suma(n1, n2)
        End Function
        
        Public Function sumaAsync(ByVal n1 As Double, ByVal n2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.sumaAsync
            Return MyBase.Channel.sumaAsync(n1, n2)
        End Function
        
        Public Function Resta(ByVal n1 As Double, ByVal n2 As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.Resta
            Return MyBase.Channel.Resta(n1, n2)
        End Function
        
        Public Function RestaAsync(ByVal n1 As Double, ByVal n2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.RestaAsync
            Return MyBase.Channel.RestaAsync(n1, n2)
        End Function
        
        Public Function fac(ByVal n As Integer) As Double Implements ServiceReference1.CalculadoraServiceSoap.fac
            Return MyBase.Channel.fac(n)
        End Function
        
        Public Function facAsync(ByVal n As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.facAsync
            Return MyBase.Channel.facAsync(n)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_CalculadoraServiceSoap_div(ByVal request As ServiceReference1.divRequest) As ServiceReference1.divResponse Implements ServiceReference1.CalculadoraServiceSoap.div
            Return MyBase.Channel.div(request)
        End Function
        
        Public Function div(ByVal n1 As Double, ByVal n2 As Double) As String
            Dim inValue As ServiceReference1.divRequest = New ServiceReference1.divRequest()
            inValue.Body = New ServiceReference1.divRequestBody()
            inValue.Body.n1 = n1
            inValue.Body.n2 = n2
            Dim retVal As ServiceReference1.divResponse = CType(Me,ServiceReference1.CalculadoraServiceSoap).div(inValue)
            Return retVal.Body.divResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_CalculadoraServiceSoap_divAsync(ByVal request As ServiceReference1.divRequest) As System.Threading.Tasks.Task(Of ServiceReference1.divResponse) Implements ServiceReference1.CalculadoraServiceSoap.divAsync
            Return MyBase.Channel.divAsync(request)
        End Function
        
        Public Function divAsync(ByVal n1 As Double, ByVal n2 As Double) As System.Threading.Tasks.Task(Of ServiceReference1.divResponse)
            Dim inValue As ServiceReference1.divRequest = New ServiceReference1.divRequest()
            inValue.Body = New ServiceReference1.divRequestBody()
            inValue.Body.n1 = n1
            inValue.Body.n2 = n2
            Return CType(Me,ServiceReference1.CalculadoraServiceSoap).divAsync(inValue)
        End Function
        
        Public Function Multiplicacion(ByVal n1 As Double, ByVal n2 As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.Multiplicacion
            Return MyBase.Channel.Multiplicacion(n1, n2)
        End Function
        
        Public Function MultiplicacionAsync(ByVal n1 As Double, ByVal n2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.MultiplicacionAsync
            Return MyBase.Channel.MultiplicacionAsync(n1, n2)
        End Function
        
        Public Function Potencia(ByVal Base As Double, ByVal Exponente As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.Potencia
            Return MyBase.Channel.Potencia(Base, Exponente)
        End Function
        
        Public Function PotenciaAsync(ByVal Base As Double, ByVal Exponente As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.PotenciaAsync
            Return MyBase.Channel.PotenciaAsync(Base, Exponente)
        End Function
        
        Public Function RaizCuadrada(ByVal Radicando As Double, ByVal indice As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.RaizCuadrada
            Return MyBase.Channel.RaizCuadrada(Radicando, indice)
        End Function
        
        Public Function RaizCuadradaAsync(ByVal Radicando As Double, ByVal indice As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.RaizCuadradaAsync
            Return MyBase.Channel.RaizCuadradaAsync(Radicando, indice)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_CalculadoraServiceSoap_Inverso(ByVal request As ServiceReference1.InversoRequest) As ServiceReference1.InversoResponse Implements ServiceReference1.CalculadoraServiceSoap.Inverso
            Return MyBase.Channel.Inverso(request)
        End Function
        
        Public Function Inverso(ByVal n1 As Double) As String
            Dim inValue As ServiceReference1.InversoRequest = New ServiceReference1.InversoRequest()
            inValue.Body = New ServiceReference1.InversoRequestBody()
            inValue.Body.n1 = n1
            Dim retVal As ServiceReference1.InversoResponse = CType(Me,ServiceReference1.CalculadoraServiceSoap).Inverso(inValue)
            Return retVal.Body.InversoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_CalculadoraServiceSoap_InversoAsync(ByVal request As ServiceReference1.InversoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.InversoResponse) Implements ServiceReference1.CalculadoraServiceSoap.InversoAsync
            Return MyBase.Channel.InversoAsync(request)
        End Function
        
        Public Function InversoAsync(ByVal n1 As Double) As System.Threading.Tasks.Task(Of ServiceReference1.InversoResponse)
            Dim inValue As ServiceReference1.InversoRequest = New ServiceReference1.InversoRequest()
            inValue.Body = New ServiceReference1.InversoRequestBody()
            inValue.Body.n1 = n1
            Return CType(Me,ServiceReference1.CalculadoraServiceSoap).InversoAsync(inValue)
        End Function
        
        Public Function Seno(ByVal n1 As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.Seno
            Return MyBase.Channel.Seno(n1)
        End Function
        
        Public Function SenoAsync(ByVal n1 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.SenoAsync
            Return MyBase.Channel.SenoAsync(n1)
        End Function
        
        Public Function Coseno(ByVal n1 As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.Coseno
            Return MyBase.Channel.Coseno(n1)
        End Function
        
        Public Function CosenoAsync(ByVal n1 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.CosenoAsync
            Return MyBase.Channel.CosenoAsync(n1)
        End Function
        
        Public Function Tangente(ByVal n1 As Double) As Double Implements ServiceReference1.CalculadoraServiceSoap.Tangente
            Return MyBase.Channel.Tangente(n1)
        End Function
        
        Public Function TangenteAsync(ByVal n1 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.CalculadoraServiceSoap.TangenteAsync
            Return MyBase.Channel.TangenteAsync(n1)
        End Function
    End Class
End Namespace
